# Generated by Django 5.2.8 on 2025-12-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_pedido_options_alter_turno_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_pedido'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
    ]
