# Generated by Django 5.2.8 on 2025-12-04 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_pedido_options_alter_turno_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_servicio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='hora_servicio',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='orders.turno', verbose_name='Turno'),
        ),
    ]
