# Generated by Django 5.2.8 on 2025-12-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_pedido_fecha_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.turno', verbose_name='Turno'),
        ),
    ]
