# Generated by Django 5.2.8 on 2025-12-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_pedido_precio_total_alter_pedido_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_combustible',
            field=models.CharField(choices=[('gasolina_95', 'Gasolina 95'), ('gasolina_98', 'Gasolina 98'), ('diesel', 'Diésel')], default='', max_length=20, verbose_name='Tipo de combustible'),
            preserve_default=False,
        ),
    ]
