# Generated by Django 5.2.8 on 2025-12-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_pedido_tipo_combustible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_combustible',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_servicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de servicio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_servicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de servicio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio total'),
        ),
    ]
