# Generated by Django 5.2.8 on 2025-12-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_apellidos_alter_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasenya',
            field=models.CharField(default='', max_length=255, verbose_name='Contrasenya'),
            preserve_default=False,
        ),
    ]
