# Generated by Django 5.2.8 on 2025-12-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usuario_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
    ]
