# Generated by Django 5.2.8 on 2026-01-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
