# Generated by Django 5.2.8 on 2025-12-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_reembolso_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='reembolso',
            options={'verbose_name': 'Reembolso', 'verbose_name_plural': 'Reembolsos'},
        ),
    ]
