# Generated by Django 5.2.8 on 2025-12-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_pago_options_alter_reembolso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='reembolso',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Reembolso', 'verbose_name_plural': 'Reembolsos'},
        ),
    ]
