# Generated by Django 5.2.8 on 2025-12-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharges', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recarga',
            constraint=models.UniqueConstraint(fields=('tipo_combustible',), name='unique_tipo_combustible'),
        ),
    ]
