# Generated by Django 5.2.8 on 2025-12-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recharges', '0002_recarga_unique_tipo_combustible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recarga',
            options={'verbose_name': 'Recarga', 'verbose_name_plural': 'Recargas'},
        ),
        migrations.RemoveConstraint(
            model_name='recarga',
            name='unique_tipo_combustible',
        ),
    ]
