# Generated by Django 5.2.8 on 2025-12-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recharges', '0003_alter_recarga_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recarga',
            options={'ordering': ['tipo_combustible'], 'verbose_name': 'Recarga', 'verbose_name_plural': 'Recargas'},
        ),
    ]
