# Generated by Django 5.2.8 on 2025-12-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usuario_contraseña_usuario_contrasenya'),
        ('vehicles', '0002_alter_vehiculo_color_alter_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('matricula',), name='unique_matricula'),
        ),
    ]
