# Generated by Django 5.2.8 on 2025-12-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehiculo_unique_matricula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.RemoveConstraint(
            model_name='vehiculo',
            name='unique_matricula',
        ),
    ]
