# Generated by Django 5.2.8 on 2025-12-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehiculo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['marca', 'modelo', 'matricula'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
    ]
