# Generated by Django 5.2.8 on 2025-12-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='anyo_compra',
            field=models.IntegerField(default=0, verbose_name='Año de compra'),
        ),
    ]
