# Generated by Django 5.2.8 on 2025-12-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificacion_fecha_envio_and_more'),
        ('orders', '0003_alter_pedido_ubicacion_alter_pedido_vehiculo_and_more'),
        ('users', '0003_remove_usuario_contraseña_usuario_contrasenya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.UniqueConstraint(fields=('pedido', 'tipo'), name='unique_tipo_por_pedido'),
        ),
    ]
