# Generated by Django 5.2.8 on 2025-12-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
